language: node_js
node_js:
  - "6.3.0"
  - "5.12"
  - "4.4.7"
before_install:
  - npm set progress=false
  # - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))' "$PATH")
install: npm install
before_script:
  # - node_modules/.bin/grunt --version
  - node_modules/.bin/grunt test
script: echo "Done!"
