language: node_js
node_js:
  - "5.12"
  - "4.4.7"
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
before_install:
  - npm set progress=false
install: npm install
before_script:
  - node_modules/.bin/grunt test
script: echo "Done!"
